### ISSUE TITLE
Compatibility with monorepos (multi-procfile buildpack)?

### ISSUE THREAD

**Issue by ddahan** [moneymeets/python-poetry-buildpack#58]
What is the right way to use this buildback, while using [Heroku Multi Procfile buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-multi-procfile) in the same time?

I tried this way:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/1933516/218738547-1a63bc27-7ab3-49f6-9563-4c144e655ed8.png">

My Python app (and Procfile) is in `back/` folder of my root repo. Obviously, I soon as I tried to deploy, I get this error:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/1933516/218739780-835ac0a8-6c5f-4d29-ba42-ebbac2272652.png">

Any idea? workaround? Thanks.

**Comment by zyv** [comment]
> My Python app (and Procfile) is in `back/` folder of my root repo. Obviously, I soon as I tried to deploy, I get this error:

I don't think that this is related to Heroku Multi Procfile buildpack. This is how we detect a compatible app:

https://github.com/moneymeets/python-poetry-buildpack/blob/fe3ac68aa266ba50693dd2d0ea4c7eab6280cf03/bin/detect#L7

(we look for `poetry.lock` in the root folder of the app)

Even if we would add some way to specify a custom path for `poetry.lock`, then I'm pretty sure that then next buildpack (Python) will fail, because it expects `requirements.txt` in the root directory:

https://github.com/heroku/heroku-buildpack-python/blob/59e24ef8bbda64832b5dcc0145404ac73fa8f3cf/bin/detect#L18

We could of course generate `requirements.txt` in the root directory, but this sounds very questionable.

I believe that this is out of the scope of this buildpack. There are several external solutions for apps in subdirectories that generally work for all buildpacks:

1. Symlink project files like `pyproject.toml` and `poetry.lock`
2. Use standalone or inline buildpack to move the source code
    * https://github.com/timanovsky/subdir-heroku-buildpack
    * https://jtway.co/deploying-subdirectory-projects-to-heroku-f31ed65f3f2
3. Using subtree push 

I think that's enough poison to pick from...

**Comment by ddahan** [comment]
Thanks for the detailed answer. I didn't know about subdir heroku buildpack!
