### ISSUE TITLE
Supports pip version specification strings

### ISSUE THREAD

**Issue by lexicalunit** [moneymeets/python-poetry-buildpack#6]
Typically you'd want to specify your python version like:

```toml
python = '>=3.7,<4'
```

or perhaps more reasonably:

```toml
python = '^3.7.6'
```

For a new project that intends to support Python 3.7+. However nether of these options work and will fail with an error like:

```
remote: -----> Export Python version from Poetry to Heroku runtime.txt file
remote: -----> '^3.7.6' not valid, please specify an exact Python version (e.g. 3.8.1) in your pyproject.toml (and thus poetry.lock)
```

It would be nice if the latest supported version of python, given the specification string, were automatically picked.

**Comment by zyv** [comment]
@lexicalunit that’s valid idea, but we are not particularly interested, because we don’t want Heroku to change runtime versions under our feet during the next deployment, especially for major versions.

Maybe it’s an irrelevant concern for smaller or hobby projects, but every Python upgrade things just go wrong, so one first needs to figure out the dependencies, then get the test suite to pass, and only after that actually bump the runtime.

In as far as the generic restriction resolution is concerned, it is very complicated and I don’t think there is any chance for us to integrate it. Regarding the simpler case you mentioned - we would take a PR if it looks sane enough and doesn’t break anything else, but I have two concerns:

* I’m not sure what Poetry does to the Python version - does it also make it a part of lock or not? If yes, then it is to consider, what’s less surprising for the user - take it from the lock or from `pyproject.toml` - but then again, user-resolved runtime might be valid, but not supported be Heroku, what then? If it’s not taken from the lock, it might be not what the user expected it to be (higher).

* I’m not sure where the knowledge of the supported versions by Heroku would come from. We certainly wouldn’t want to hardcode and then have to regularly update it...

**Comment by lexicalunit** [comment]
What if `python-poetry-buildpack` used an existing `runtime.txt` file if one exists? Perhaps it could warn that it's using an existing file instead of creating one. Or perhaps you could opt-in to it somehow, for example:

```shell
heroku config:set PYTHON_POETRY_BUILDPACK_CREATE_RUNTIME_FILE="no"
```

And then the `compile` script would key off of that environment variable. If not set it would fallback the the current behavior for backwards compatibility.

This way the `pyproject.toml` could keep a pip version specification like `python = '>=3.7,<4'` but you'd still be able to use `python-poetry-buildpack` as long as you selected a runtime via `runtime.txt`.

**Comment by furious-luke** [comment]
Hey @lexicalunit! I found I had a very similar requirement to you, and so have created a PR to implement (almost) exactly what you asked for: https://github.com/moneymeets/python-poetry-buildpack/pull/10

The only difference is I used the config variable `POETRY_CREATE_RUNTIME_FILE`, just seemed a little more terse and I thought it was unlikely to cause a clash.

**Comment by lexicalunit** [comment]
@furious-luke sweet!
