### ISSUE TITLE
Buildpacks.io

### ISSUE THREAD

**Issue by tomh4** [moneymeets/python-poetry-buildpack#69]
Hello,

I have forked your repo and modified it as such as to have an action which deploys the buildpack to buildpacks.io when creating a release.

Would you be interested in merging this? I'd create a PR if yes

**Comment by zyv** [comment]
Hi @tomh4 , thanks for your kind offer, but I'm afraid that we will have to decline it.

We are currently moving away from Heroku, because the service has degraded over years beyond the level that we can tolerate, and we are not going to use CNB stuff for our new services, at least not at the beginning.

Therefore we will probably eventually have to start looking for a new maintainer for this buildpack. Under these circumstances it doesn't sound like a good idea to push it officially to buildpacks.io and entice more people to become dependant on it.

/cc @marns93 @mm-felixh @mm-matthias

**Comment by tomh4** [comment]
Okay I understand, I'd be interested in maintaining it as I am depending on this and it is currently the only viable solution for poetry in combination with any of the heroku build packs (we are not using heroku at all)
