### ISSUE TITLE
Python Version not identified correctly

### ISSUE THREAD

**Issue by hotzenklotz** [moneymeets/python-poetry-buildpack#8]
Hi. My heroku build crashes with the following error:

```
-----> Export Python version from Poetry to Heroku runtime.txt file
-----> ^3.7 not valid, please specify an exact Python version (e.g. 3.8.1) in your pyproject.toml (and thus poetry.lock)
```

My `pyproject.toml` contains a valid python version specification, following the recommendations in the [Poetry documentation](https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies). According to the Poetry docs the `^` syntax should be valid.
```
[tool.poetry.dependencies]
python = "^3.7"
```

I am not exactly sure what I am doing wrong? Do I have the wrong Python version specification/different attribute name in `pyproject.toml`? Any pointers, why it is complaining? Thanks.

**Comment by zyv** [comment]
Hi,

The error message that you are getting pretty much says it all:

> ^3.7 not valid, please specify an exact Python version (e.g. 3.8.1) in your pyproject.toml (and thus poetry.lock)

We understand that this limitation comes across as annoying for some users, but we simply couldn't find a better & still simple enough solution to serve our needs so far - the background is explained in details in #6.

I think the best way to go about it is indeed to allow suppressing the generation of `runtime.txt`, but unfortunately we didn't get around to it yet.

All the best,
Yury

**Comment by hotzenklotz** [comment]
I understand your point above version stability in #6 . This might be true for major and minor versions. I don't quite understand why this should be the case for patch versions as well. It should make any different if I use `3.7.1` or `3.7.5`.

So, I guess I should have written `~3.7` to pin the version to `3.7` and all all `patch`versions. (e.g. `3.7.x`) Could you parse that?

**Comment by zyv** [comment]
> I don't quite understand why this should be the case for patch versions as well.

One could argue, that patch versions can also wreak havoc, but I wouldn't do that - the real problem is that `runtime.txt` doesn't support patterns. This means that we can't just give `~3.7` to `runtime.txt` and be done with it. We would have to parse your input, match that against all available runtimes (where should we get this info from? currently this is published on a Heroku documentation web page, which is not easily parsable) and pick one that satisfies the pattern.

So I think that the only practicable solution at the moment is to either set a specific version and write it into `runtime.txt` or suppress the `runtime.txt` generation altogether, and let Heroku simply pick the default runtime whatever it is at any given point in time...

**Comment by hotzenklotz** [comment]
Thanks for the advice.
